apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
data:
  namespace: namespace
  cluster-description-1: description-1
  cluster-description-2: description-1
  cluster-name-1: cluster-1
  cluster-name-2: cluster-2
  project-id: project
  region: region
  tags-1: |
    - zonal
    - demo
  tags-2: |
    - zonal
    - demo
  zone: zone
  auth-network: auth-net
  repo: repo
  branch: branch
