apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata: # kpt-merge: ${NAMESPACE}/gkehubfeature-acm
  name: gkehubfeature-acm
  namespace: config-control # kpt-set: ${namespace}
  labels:
    feature: acm
  annotations:
    cnrm.cloud.google.com/project-id: project # kpt-set: ${project-id}
spec:
  location: global
  projectRef:
    external: project # kpt-set: ${project-id}
  # The resourceID must be "configmanagement" if you want to use Anthos config
  # management feature.
  resourceID: configmanagement
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata: # kpt-merge: namespace/cluster-1-mci
  name: dev-mci # kpt-set: ${cluster-name-1}-mci
  namespace: config-control # kpt-set: ${namespace}
spec:
  spec:
    multiclusteringress:
      configMembershipRef:
        name: dev-hub # kpt-set: ${cluster-name-1}-hub
  location: global
  projectRef:
    name: project # kpt-set: ${project-id}
  # The resourceID must be "multiclusteringress" if you want to use multi-cluster
  # ingress feature.
  resourceID: multiclusteringress
