apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata: # kpt-merge: ${NAMESPACE}/gkehubfeature-acm
  name: gkehubfeature-acm
  namespace: namespace # kpt-set: ${namespace}
  labels:
    feature: acm
  annotations:
    cnrm.cloud.google.com/project-id: ${PROJECT_ID} # kpt-set: ${project}
spec:
  location: global
  projectRef:
    external: project # kpt-set: ${project-id}
  # The resourceID must be "configmanagement" if you want to use Anthos config
  # management feature.
  resourceID: configmanagement
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: cluster-1-mci # kpt-set: ${cluster-name-1}-mci
  namespace: namespace # kpt-set: ${namespace}
spec:
  projectRef:
    name: project # kpt-set: ${project-id}
  location: global
  # The resourceID must be "multiclusteringress" if you want to use multi-cluster
  # ingress feature.
  resourceID: multiclusteringress
  spec:
    multiclusteringress:
      configMembershipRef:
        name: cluster-1-hub # kpt-set: ${cluster-name-1}-hub
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: cluster-2-mci # kpt-set: ${cluster-name-2}-mci
  namespace: namespace # kpt-set: ${namespace}
spec:
  projectRef:
    external: project # kpt-set: ${project-id}
  location: global
  # The resourceID must be "multiclusteringress" if you want to use multi-cluster
  # ingress feature.
  resourceID: multiclusteringress
  spec:
    multiclusteringress:
      configMembershipRef:
        name: cluster-2-hub # kpt-set: ${cluster-name-2}-hub
