apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata: # kpt-merge: ${NAMESPACE}/gkehub-${CLUSTER_NAME}
  name: baremetal-dev
  namespace: config-control # kpt-set: ${namespace}
spec:
  configmanagement:
    binauthz:
      enabled: false
    configSync:
      git:
        policyDir: ""
        secretType: "none"
        syncBranch: main # kpt-set: ${branch}
        syncRepo: github # kpt-set: ${repo}
        syncRev: "HEAD"
        syncWaitSecs: "20"
      sourceFormat: hierarchy
    policyController:
      auditIntervalSeconds: "20"
      enabled: true
      exemptableNamespaces:
        - "config-management-system"
        - "falco-system"
        - "csi-driver"
      logDeniesEnabled: true
      referentialRulesEnabled: true
      templateLibraryInstalled: true
    version: 1.8.1
  featureRef:
    name: gkehubfeature-acm
  location: global
  membershipRef:
    external: dev-hub # kpt-set: ${cluster-name-1}-hub
  projectRef:
    external: project # kpt-set: ${project-id}
