apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: my-super-secret-secret
  namespace: config-control # kpt-set: ${namespace}  
  labels:
    replication-type: user-managed
spec:
  replication:
    userManaged:
      replicas:
        - location: northamerica-northeast1
        - location: northamerica-northeast2
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  name: secretmanagersecretversion-sample
  namespace: config-control # kpt-set: ${namespace}
spec:
  secretRef:
    name: my-super-secret-secret
  enabled: true
  secretData:
    value: secret-squirel
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: gke-workload
  namespace: config-control # kpt-set: ${namespace}     
  labels:
    label-one: "value-one"
spec:
  displayName: gke-workload user
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: workloadid-user
  namespace: config-control # kpt-set: ${namespace}  
spec:
  member: serviceAccount:project.svc.id.goog[secret-app/mypodserviceaccount] # kpt-set: serviceAccount:${project-id}.svc.id.goog[secret-app/mypodserviceaccount]
  resourceRef:
    name: gke-workload@project.iam.gserviceaccount.com # kpt-set: gke-workload@${project-id}.iam.gserviceaccount.com
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
  role: roles/iam.workloadIdentityUser
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: secret-user
  namespace: config-control # kpt-set: ${namespace}  
spec:
  member: serviceAccount:gke-workload@project.iam.gserviceaccount.com # kpt-set: serviceAccount:gke-workload@${project-id}.iam.gserviceaccount.com
  resourceRef:
    name: my-super-secret-secret
    apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
    kind: SecretManagerSecret
  role: roles/secretmanager.secretAccessor
