apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata: # kpt-merge: ${NAMESPACE}/gkehubfeature-dep-acmfeature-2
  name: anthos-configmanagement
  namespace: namespace # kpt-set: ${namespace}
  annotations:
    cnrm.cloud.google.com/disable-dependent-services: "false"
    cnrm.cloud.google.com/project-id: project # kpt-set: ${project-id}
spec:
  resourceID: anthosconfigmanagement.googleapis.com
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: multicluster-ingress
spec:
  resourceID: multiclusteringress.googleapis.com
  projectRef:
    external: project # kpt-set: ${project-id}
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: gkehub
spec:
  resourceID: gkehub.googleapis.com
  projectRef:
    external: project # kpt-set: ${project-id}
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: container
spec:
  resourceID: container.googleapis.com
  projectRef:
    external: project # kpt-set: ${project-id}
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: multicluster-service
spec:
  resourceID: multiclusterservicediscovery.googleapis.com
  projectRef:
    external: project # kpt-set: ${project-id}
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: project # kpt-set: ${project-id}
  name: binaryauthorization
spec:
  resourceID: binaryauthorization.googleapis.com
